name: Lodestone Technologies
favicon: null
layout_spectrum: 0.44341
typography_spectrum: 0.05117857735604048
title: Lodestone
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8125
  lightness: 0.2874604216776788
  saturation: 0.39580728439614177
  rhythmicContrast: 0.8238244706299156
purpose: []
