name: Lodestone Technologies
favicon: null
layout_spectrum: 0.25415
typography_spectrum: 0.68605
title: Lodestone
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d0c7be'
    - '#5e6f76'
    - '#fefefe'
    - '#05f01d'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.8238244706299156
purpose: []
